dist: trusty
language: minimal
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - nvm install node
  - npm --version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3 # https://yarnpkg.com/lang/en/docs/install-ci/
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version
install:
  #- rm -rf ./node_modules
  - yarn install
script:
  - yarn build
  - rm -rf public/dist
  - mv dist/ public/dist/
deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: projects.snowme34.com
  on:
    branch: master
